"""
research/cached_walk_forward_runner.py
----------------------------------------
S5: Wire walk-forward skeleton to cached candidate evaluation.

Connects CandidateSpec, WalkForwardSplit, evaluate_walk_forward(),
run_cached_candidate_evaluation(), and validate_candidate_metrics()
through an injected per-split evaluator.

Split-date slicing is NOT yet implemented in S5. The default split
evaluator calls run_cached_candidate_evaluation() with the full cached
file for each split; the backtest runs over the entire cached date range
regardless of train/test boundaries. A follow-on PR (S5b or S6) will
add per-split date filtering.

Safety flags:
  broker_calls_made, credentials_read, network_calls_made,
  order_action_requested, live_trading_allowed — all always False.

This module does not import from broker adapters, live tools, environment
variables, network libraries, or execution layers. No order submission.
No file writes. No output artifacts. No parameter optimization.
"""

from __future__ import annotations

import logging
import pathlib
from dataclasses import dataclass
from typing import Any

from src.research.cached_candidate_runner import run_cached_candidate_evaluation
from src.research.candidate_evaluator import (
    REQUIRED_METRIC_KEYS,
    CandidateEvaluationResult,
)
from src.research.candidate_universe import CandidateSpec
from src.research.metrics_validation import MetricsValidationResult, validate_candidate_metrics
from src.research.walk_forward import (
    WalkForwardSplit,
    build_walk_forward_splits,
    evaluate_walk_forward,
)

logger = logging.getLogger(__name__)

_SAFETY: dict[str, Any] = dict(
    broker_calls_made=False,
    credentials_read=False,
    network_calls_made=False,
    order_action_requested=False,
    live_trading_allowed=False,
)


# ---------------------------------------------------------------------------
# Result type
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class CachedWalkForwardRunResult:
    """Immutable aggregate result of run_cached_walk_forward_evaluation().

    result is "PASS", "BLOCKED", or "ERROR".
    split_results: per-split CandidateEvaluationResult in chronological order.
    validation_results: per-split MetricsValidationResult in the same order.
    splits_requested: total splits generated by build_walk_forward_splits().
    splits_evaluated: splits for which the evaluator was called.
    All safety flags are always False.
    """
    result: str
    blocker: str | None
    candidate_id: str
    splits_requested: int
    splits_evaluated: int
    split_results: tuple[CandidateEvaluationResult, ...]
    validation_results: tuple[MetricsValidationResult, ...]
    broker_calls_made: bool      # always False
    credentials_read: bool       # always False
    network_calls_made: bool     # always False
    order_action_requested: bool # always False
    live_trading_allowed: bool   # always False


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _make_blocked_eval_result(
    candidate: CandidateSpec,
    blocker: str,
) -> CandidateEvaluationResult:
    return CandidateEvaluationResult(
        candidate_id=candidate.candidate_id,
        symbol=candidate.symbol,
        interval=candidate.interval,
        strategy_family=candidate.strategy_family.value,
        result="BLOCKED",
        blocker=blocker,
        metrics={k: None for k in REQUIRED_METRIC_KEYS},
        broker_calls_made=False,
        credentials_read=False,
        network_calls_made=False,
        order_action_requested=False,
        live_trading_allowed=False,
    )


def _make_default_split_evaluator(cache_dir: pathlib.Path | None):
    """Return a per-split evaluator backed by run_cached_candidate_evaluation().

    The evaluator delegates to the S3 cached runner for each split.
    Split-date slicing is not yet implemented: the full cached file is used
    for every split regardless of train/test boundaries.
    """
    def evaluator(
        candidate: CandidateSpec,
        split: WalkForwardSplit,
    ) -> CandidateEvaluationResult:
        run_result = run_cached_candidate_evaluation(
            [candidate],
            cache_dir=cache_dir,
            max_candidates=1,
        )
        if run_result.results:
            return run_result.results[0]
        return _make_blocked_eval_result(
            candidate, "cached evaluation returned no result"
        )

    return evaluator


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def run_cached_walk_forward_evaluation(
    candidate: CandidateSpec,
    *,
    start_date: str,
    end_date: str,
    train_months: int,
    test_months: int,
    step_months: int,
    cache_dir: str | pathlib.Path | None = None,
    _split_evaluator=None,
) -> CachedWalkForwardRunResult:
    """Evaluate a candidate across walk-forward splits using cached bar data.

    Parameters
    ----------
    candidate:
        The CandidateSpec to evaluate across all splits.
    start_date:
        ISO-8601 start of the full date range (inclusive).
    end_date:
        ISO-8601 end of the full date range (inclusive).
    train_months:
        Width of each training window in calendar months. Must be >= 1.
    test_months:
        Width of each test window in calendar months. Must be >= 1.
    step_months:
        Step size between successive train_start dates.
        Must be >= test_months to keep test windows non-overlapping.
    cache_dir:
        Directory containing .parquet or .csv cache files.
        Defaults to "data/cache" (used by the default split evaluator).
    _split_evaluator:
        Test injection: callable(candidate, split) → CandidateEvaluationResult.
        When None, the default cached evaluator is used.

    Returns
    -------
    CachedWalkForwardRunResult
        result="PASS"    when all splits passed and all metrics validated.
        result="BLOCKED" when ≥1 split was BLOCKED, or ≥1 metrics validation
                         was BLOCKED, or walk-forward config was invalid.
        result="ERROR"   when ≥1 split returned ERROR.
        All safety flags are always False.

    Notes
    -----
    Build-split ValueError (e.g. step_months < test_months, invalid dates)
    → BLOCKED with blocker "invalid walk-forward configuration: ...".

    No splits generated → BLOCKED("no walk-forward splits generated ...").

    Per-split metrics validation: each PASS split result has its metrics
    validated by validate_candidate_metrics(). A validation BLOCKED does not
    mutate the original CandidateEvaluationResult; it contributes to the
    aggregate result independently.

    Aggregation priority: ERROR > BLOCKED > PASS.

    Split-date slicing is not yet implemented (S5 scope). The default
    evaluator runs the full cached backtest for every split.

    This function never reads credentials, contacts brokers, makes network
    calls, submits orders, or writes files.
    """
    cache_path = (
        pathlib.Path(cache_dir) if cache_dir is not None else None
    )

    # 1. Build walk-forward splits (ValueError → BLOCKED).
    try:
        splits = build_walk_forward_splits(
            start_date=start_date,
            end_date=end_date,
            train_months=train_months,
            test_months=test_months,
            step_months=step_months,
        )
    except ValueError as exc:
        return CachedWalkForwardRunResult(
            result="BLOCKED",
            blocker=f"invalid walk-forward configuration: {exc}",
            candidate_id=candidate.candidate_id,
            splits_requested=0,
            splits_evaluated=0,
            split_results=(),
            validation_results=(),
            **_SAFETY,
        )

    if not splits:
        return CachedWalkForwardRunResult(
            result="BLOCKED",
            blocker="no walk-forward splits generated for the given date range",
            candidate_id=candidate.candidate_id,
            splits_requested=0,
            splits_evaluated=0,
            split_results=(),
            validation_results=(),
            **_SAFETY,
        )

    # 2. Resolve split evaluator.
    split_evaluator = _split_evaluator or _make_default_split_evaluator(cache_path)

    # 3. Evaluate all splits (evaluate-all policy, exceptions → ERROR per split).
    wf_result = evaluate_walk_forward(
        candidate, splits, split_evaluator=split_evaluator
    )

    # 4. Validate metrics for each split result.
    validation_results: list[MetricsValidationResult] = [
        validate_candidate_metrics(sr.metrics)
        for sr in wf_result.split_results
    ]

    # 5. Aggregate: ERROR > BLOCKED > PASS.
    n_error = sum(1 for r in wf_result.split_results if r.result == "ERROR")
    n_split_blocked = sum(1 for r in wf_result.split_results if r.result == "BLOCKED")
    n_val_blocked = sum(1 for v in validation_results if v.result == "BLOCKED")

    if n_error > 0:
        overall = "ERROR"
        blocker: str | None = f"{n_error} split(s) returned ERROR"
    elif n_split_blocked > 0 or n_val_blocked > 0:
        overall = "BLOCKED"
        parts: list[str] = []
        if n_split_blocked > 0:
            parts.append(f"{n_split_blocked} split(s) BLOCKED")
        if n_val_blocked > 0:
            parts.append(f"{n_val_blocked} split(s) failed metrics validation")
        blocker = "; ".join(parts)
    else:
        overall = "PASS"
        blocker = None

    return CachedWalkForwardRunResult(
        result=overall,
        blocker=blocker,
        candidate_id=candidate.candidate_id,
        splits_requested=wf_result.splits_requested,
        splits_evaluated=wf_result.splits_evaluated,
        split_results=wf_result.split_results,
        validation_results=tuple(validation_results),
        **_SAFETY,
    )
